// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AzureBooksApp.Models;

public partial class BookWithAuthor
{
    public int BookId { get; set; }

    public string BookTitle { get; set; }

    public int? YearPublished { get; set; }

    public int AuthorId { get; set; }

    public string AuthorName { get; set; }
}